# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Userss = [
    {first_name: "Admin", last_name: "Admin", email: "admin@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: true, role: 2, username: "admin", password: "admin123"},
    {first_name: "Mario", last_name: "Rossi", email: "advanceduser@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 1, username: "advanceduser", password: "advanceduser123"},
    {first_name: "Francesco", last_name: "Bianchi", email: "advanceduser1@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 1, username: "advanceduser", password: "advanceduser123"},
    {first_name: "Alessio", last_name: "Gialli", email: "advanceduser2@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 1, username: "advanceduser", password: "advanceduser123"},
    {first_name: "Federica", last_name: "Neri", email: "advanceduser3@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 1, username: "advanceduser", password: "advanceduser123"},
    {first_name: "Alice", last_name: "Russo", email: "advanceduser4@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 1, username: "advanceduser", password: "advanceduser123"},
    {first_name: "Simone", last_name: "Di Pietro", email: "advanceduser5@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 1, username: "advanceduser", password: "advanceduser123"},
    {first_name: "Anna", last_name: "Verdi", email: "user@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 0, username: "user", password: "user123"},
    {first_name: "Tiziano", last_name: "Celeste", email: "user1@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 0, username: "user", password: "user123"},
    {first_name: "Mauro", last_name: "Viola", email: "user2@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 0, username: "user", password: "user123"},
    {first_name: "Alessia", last_name: "Rossi", email: "user3@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 0, username: "user", password: "user123"},
    {first_name: "Piero", last_name: "Bianchi", email: "user4@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 0, username: "user", password: "user123"},
    {first_name: "Giuseppe", last_name: "Verdi", email: "user5@openproject.it", description: "Questa è la mia descrizione", location: "Roma", admin: false, role: 0, username: "user", password: "user123"}
 ]

Projectss = [
    {teamleader_id: 2, title: "Applicazione web con Angular", description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        In efficitur sapien felis, vel lobortis nisi lobortis in. Praesent tincidunt arcu in mi varius, sit amet scelerisque purus tristique. Pellentesque eget orci vitae erat venenatis porttitor. Donec a mi massa. Donec faucibus elit mauris, ullamcorper rhoncus nisi euismod in. Aenean vulputate eleifend orci, in rhoncus turpis lobortis at. Fusce sed ante a est aliquet fringilla. Morbi nulla nunc, hendrerit a cursus et, iaculis vitae quam. Pellentesque sit amet ultrices elit, eu eleifend ipsum. In non dolor bibendum, tristique nisi sit amet, aliquet mauris. Nullam laoreet eu odio vel consectetur. Sed sit amet augue eu eros volutpat aliquet sit amet nec arcu. Vestibulum eget sagittis enim.
        
        Phasellus sit amet urna et erat finibus pellentesque. Mauris ac odio in libero ultrices luctus eget id lectus. Nullam sit amet sodales sapien. Sed lobortis libero ante, eu gravida mauris facilisis ac. Nam nulla ex, maximus quis arcu ac, pulvinar elementum urna. Fusce erat mauris, dapibus non ex eu, tempus laoreet nisi. Aliquam iaculis dictum varius. Sed arcu lorem, suscipit a eros vel, placerat bibendum est. Maecenas tempus ante venenatis ex tincidunt, sit amet luctus ligula porta. Mauris non elementum tellus, eu ultrices turpis. Phasellus lectus velit, aliquet ut nisi ac, mattis sollicitudin lectus. Ut pulvinar risus eget tortor laoreet, vel luctus velit accumsan. Etiam quis diam libero. Suspendisse vehicula, nulla ac condimentum consectetur, neque libero sodales diam, a pretium mi tellus vitae enim. In id pulvinar tortor, ut iaculis orci. In ut pretium nisi, nec dictum nisl.", number_of_member: 8},
    
    {teamleader_id: 3, title: "Software JAVA gestionale", description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        In efficitur sapien felis, vel lobortis nisi lobortis in. Praesent tincidunt arcu in mi varius, sit amet scelerisque purus tristique. Pellentesque eget orci vitae erat venenatis porttitor. Donec a mi massa. Donec faucibus elit mauris, ullamcorper rhoncus nisi euismod in. Aenean vulputate eleifend orci, in rhoncus turpis lobortis at. Fusce sed ante a est aliquet fringilla. Morbi nulla nunc, hendrerit a cursus et, iaculis vitae quam. Pellentesque sit amet ultrices elit, eu eleifend ipsum. In non dolor bibendum, tristique nisi sit amet, aliquet mauris. Nullam laoreet eu odio vel consectetur. Sed sit amet augue eu eros volutpat aliquet sit amet nec arcu. Vestibulum eget sagittis enim.
    
        Phasellus sit amet urna et erat finibus pellentesque. Mauris ac odio in libero ultrices luctus eget id lectus. Nullam sit amet sodales sapien. Sed lobortis libero ante, eu gravida mauris facilisis ac. Nam nulla ex, maximus quis arcu ac, pulvinar elementum urna. Fusce erat mauris, dapibus non ex eu, tempus laoreet nisi. Aliquam iaculis dictum varius. Sed arcu lorem, suscipit a eros vel, placerat bibendum est. Maecenas tempus ante venenatis ex tincidunt, sit amet luctus ligula porta. Mauris non elementum tellus, eu ultrices turpis. Phasellus lectus velit, aliquet ut nisi ac, mattis sollicitudin lectus. Ut pulvinar risus eget tortor laoreet, vel luctus velit accumsan. Etiam quis diam libero. Suspendisse vehicula, nulla ac condimentum consectetur, neque libero sodales diam, a pretium mi tellus vitae enim. In id pulvinar tortor, ut iaculis orci. In ut pretium nisi, nec dictum nisl.", number_of_member: 5},
    
    {teamleader_id: 4, title: "Gioco multiplayer Unity3D", description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        In efficitur sapien felis, vel lobortis nisi lobortis in. Praesent tincidunt arcu in mi varius, sit amet scelerisque purus tristique. Pellentesque eget orci vitae erat venenatis porttitor. Donec a mi massa. Donec faucibus elit mauris, ullamcorper rhoncus nisi euismod in. Aenean vulputate eleifend orci, in rhoncus turpis lobortis at. Fusce sed ante a est aliquet fringilla. Morbi nulla nunc, hendrerit a cursus et, iaculis vitae quam. Pellentesque sit amet ultrices elit, eu eleifend ipsum. In non dolor bibendum, tristique nisi sit amet, aliquet mauris. Nullam laoreet eu odio vel consectetur. Sed sit amet augue eu eros volutpat aliquet sit amet nec arcu. Vestibulum eget sagittis enim.
        
        Phasellus sit amet urna et erat finibus pellentesque. Mauris ac odio in libero ultrices luctus eget id lectus. Nullam sit amet sodales sapien. Sed lobortis libero ante, eu gravida mauris facilisis ac. Nam nulla ex, maximus quis arcu ac, pulvinar elementum urna. Fusce erat mauris, dapibus non ex eu, tempus laoreet nisi. Aliquam iaculis dictum varius. Sed arcu lorem, suscipit a eros vel, placerat bibendum est. Maecenas tempus ante venenatis ex tincidunt, sit amet luctus ligula porta. Mauris non elementum tellus, eu ultrices turpis. Phasellus lectus velit, aliquet ut nisi ac, mattis sollicitudin lectus. Ut pulvinar risus eget tortor laoreet, vel luctus velit accumsan. Etiam quis diam libero. Suspendisse vehicula, nulla ac condimentum consectetur, neque libero sodales diam, a pretium mi tellus vitae enim. In id pulvinar tortor, ut iaculis orci. In ut pretium nisi, nec dictum nisl.", number_of_member: 12},
        
    {teamleader_id: 5, title: "Orologio Arduino", description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

        In efficitur sapien felis, vel lobortis nisi lobortis in. Praesent tincidunt arcu in mi varius, sit amet scelerisque purus tristique. Pellentesque eget orci vitae erat venenatis porttitor. Donec a mi massa. Donec faucibus elit mauris, ullamcorper rhoncus nisi euismod in. Aenean vulputate eleifend orci, in rhoncus turpis lobortis at. Fusce sed ante a est aliquet fringilla. Morbi nulla nunc, hendrerit a cursus et, iaculis vitae quam. Pellentesque sit amet ultrices elit, eu eleifend ipsum. In non dolor bibendum, tristique nisi sit amet, aliquet mauris. Nullam laoreet eu odio vel consectetur. Sed sit amet augue eu eros volutpat aliquet sit amet nec arcu. Vestibulum eget sagittis enim.
            
        Phasellus sit amet urna et erat finibus pellentesque. Mauris ac odio in libero ultrices luctus eget id lectus. Nullam sit amet sodales sapien. Sed lobortis libero ante, eu gravida mauris facilisis ac. Nam nulla ex, maximus quis arcu ac, pulvinar elementum urna. Fusce erat mauris, dapibus non ex eu, tempus laoreet nisi. Aliquam iaculis dictum varius. Sed arcu lorem, suscipit a eros vel, placerat bibendum est. Maecenas tempus ante venenatis ex tincidunt, sit amet luctus ligula porta. Mauris non elementum tellus, eu ultrices turpis. Phasellus lectus velit, aliquet ut nisi ac, mattis sollicitudin lectus. Ut pulvinar risus eget tortor laoreet, vel luctus velit accumsan. Etiam quis diam libero. Suspendisse vehicula, nulla ac condimentum consectetur, neque libero sodales diam, a pretium mi tellus vitae enim. In id pulvinar tortor, ut iaculis orci. In ut pretium nisi, nec dictum nisl.", number_of_member: 8},
        
    {teamleader_id: 6, title: "API banche d'Italia", description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    
        In efficitur sapien felis, vel lobortis nisi lobortis in. Praesent tincidunt arcu in mi varius, sit amet scelerisque purus tristique. Pellentesque eget orci vitae erat venenatis porttitor. Donec a mi massa. Donec faucibus elit mauris, ullamcorper rhoncus nisi euismod in. Aenean vulputate eleifend orci, in rhoncus turpis lobortis at. Fusce sed ante a est aliquet fringilla. Morbi nulla nunc, hendrerit a cursus et, iaculis vitae quam. Pellentesque sit amet ultrices elit, eu eleifend ipsum. In non dolor bibendum, tristique nisi sit amet, aliquet mauris. Nullam laoreet eu odio vel consectetur. Sed sit amet augue eu eros volutpat aliquet sit amet nec arcu. Vestibulum eget sagittis enim.
        
        Phasellus sit amet urna et erat finibus pellentesque. Mauris ac odio in libero ultrices luctus eget id lectus. Nullam sit amet sodales sapien. Sed lobortis libero ante, eu gravida mauris facilisis ac. Nam nulla ex, maximus quis arcu ac, pulvinar elementum urna. Fusce erat mauris, dapibus non ex eu, tempus laoreet nisi. Aliquam iaculis dictum varius. Sed arcu lorem, suscipit a eros vel, placerat bibendum est. Maecenas tempus ante venenatis ex tincidunt, sit amet luctus ligula porta. Mauris non elementum tellus, eu ultrices turpis. Phasellus lectus velit, aliquet ut nisi ac, mattis sollicitudin lectus. Ut pulvinar risus eget tortor laoreet, vel luctus velit accumsan. Etiam quis diam libero. Suspendisse vehicula, nulla ac condimentum consectetur, neque libero sodales diam, a pretium mi tellus vitae enim. In id pulvinar tortor, ut iaculis orci. In ut pretium nisi, nec dictum nisl.", number_of_member: 5},
        
    {teamleader_id: 7, title: "Programma per ASL Roma", description: " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    
        In efficitur sapien felis, vel lobortis nisi lobortis in. Praesent tincidunt arcu in mi varius, sit amet scelerisque purus tristique. Pellentesque eget orci vitae erat venenatis porttitor. Donec a mi massa. Donec faucibus elit mauris, ullamcorper rhoncus nisi euismod in. Aenean vulputate eleifend orci, in rhoncus turpis lobortis at. Fusce sed ante a est aliquet fringilla. Morbi nulla nunc, hendrerit a cursus et, iaculis vitae quam. Pellentesque sit amet ultrices elit, eu eleifend ipsum. In non dolor bibendum, tristique nisi sit amet, aliquet mauris. Nullam laoreet eu odio vel consectetur. Sed sit amet augue eu eros volutpat aliquet sit amet nec arcu. Vestibulum eget sagittis enim.
            
        Phasellus sit amet urna et erat finibus pellentesque. Mauris ac odio in libero ultrices luctus eget id lectus. Nullam sit amet sodales sapien. Sed lobortis libero ante, eu gravida mauris facilisis ac. Nam nulla ex, maximus quis arcu ac, pulvinar elementum urna. Fusce erat mauris, dapibus non ex eu, tempus laoreet nisi. Aliquam iaculis dictum varius. Sed arcu lorem, suscipit a eros vel, placerat bibendum est. Maecenas tempus ante venenatis ex tincidunt, sit amet luctus ligula porta. Mauris non elementum tellus, eu ultrices turpis. Phasellus lectus velit, aliquet ut nisi ac, mattis sollicitudin lectus. Ut pulvinar risus eget tortor laoreet, vel luctus velit accumsan. Etiam quis diam libero. Suspendisse vehicula, nulla ac condimentum consectetur, neque libero sodales diam, a pretium mi tellus vitae enim. In id pulvinar tortor, ut iaculis orci. In ut pretium nisi, nec dictum nisl.", number_of_member: 12},
            
]



UserStoriess = [
    #Worker: 8-9-10 creator 2
    {project_id: 1, worker_id: 8, creator_id: 2, title: "Fare mockup", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 1, worker_id: 9, creator_id: 2, title: "Creare database", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 1, worker_id: 9, creator_id: 2, title: "Test", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 1, worker_id: 9, creator_id: 2, title: "Login Oauth", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 1, worker_id: 8, creator_id: 2, title: "Pagina HOME", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 1, worker_id: 10, creator_id: 2, title: "Pannello Admin", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 1, worker_id: 10, creator_id: 2, title: "Pannello Progetto", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 1, worker_id: 8, creator_id: 2, title: "API rest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    #Worker: 10-11-12-13 creator 3
    {project_id: 2, worker_id: 10, creator_id: 3, title: "Fare mockup", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 2, worker_id: 11, creator_id: 3, title: "Creare database", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 2, worker_id: 10, creator_id: 3, title: "Test", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 2, worker_id: 12, creator_id: 3, title: "Login Oauth", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 2, worker_id: 13, creator_id: 3, title: "Pagina HOME", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 2, worker_id: 10, creator_id: 3, title: "Pannello Admin", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 2, worker_id: 13, creator_id: 3, title: "Pannello Progetto", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 2, worker_id: 12, creator_id: 3, title: "API rest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    #Worker: 8-9-10-11-12-13 creator 4
    {project_id: 3, worker_id: 8, creator_id: 4, title: "Fare mockup", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 3, worker_id: 9, creator_id: 4, title: "Creare database", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 3, worker_id: 10, creator_id: 4, title: "Test", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 3, worker_id: 9, creator_id: 4, title: "Login Oauth", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 3, worker_id: 12, creator_id: 4, title: "Pagina HOME", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 3, worker_id: 10, creator_id: 4, title: "Pannello Admin", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 3, worker_id: 11, creator_id: 4, title: "Pannello Progetto", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 3, worker_id: 13, creator_id: 4, title: "API rest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    #Worker 9-11 creator 5
    {project_id: 4, worker_id: 11, creator_id: 5, title: "Fare mockup", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 4, worker_id: 9, creator_id: 5, title: "Creare database", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 4, worker_id: 9, creator_id: 5, title: "Test", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 4, worker_id: 9, creator_id: 5, title: "Login Oauth", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 4, worker_id: 11, creator_id: 5, title: "Pagina HOME", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 4, worker_id: :Nil, creator_id: 5, title: "Pannello Admin", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 4, worker_id: :Nil, creator_id: 5, title: "Pannello Progetto", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 4, worker_id: 9, creator_id: 5, title: "API rest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    #Worker 0 creator 6
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Fare mockup", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Creare database", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Test", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Login Oauth", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Pagina HOME", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Pannello Admin", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "Pannello Progetto", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 5, worker_id: :Nil, creator_id: 6, title: "API rest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    #Worker 13-8 creator 7
    {project_id: 6, worker_id: 13, creator_id: 7, title: "Fare mockup", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 6, worker_id: 13, creator_id: 7, title: "Creare database", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 6, worker_id: 8, creator_id: 7, title: "Test", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 6, worker_id: :Nil, creator_id: 7, title: "Login Oauth", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 1},
    {project_id: 6, worker_id: 8, creator_id: 7, title: "Pagina HOME", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 6, worker_id: 13, creator_id: 7, title: "Pannello Admin", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 2},
    {project_id: 6, worker_id: :Nil, creator_id: 7, title: "Pannello Progetto", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0},
    {project_id: 6, worker_id: :Nil, creator_id: 7, title: "API rest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut nulla justo. Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet. Fusce sed laoreet mauris. Donec porta mauris vel sapien suscipit feugiat. Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo. Proin tempor lacus arcu, id sollicitudin lacus lacinia ut. Donec sed lacinia enim. Curabitur sed blandit urna. Integer sit amet faucibus justo. Etiam malesuada ac nisl quis tristique. Duis eget vestibulum nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. ", deadline: "2019-07-10", state: 0}

]

Joinss=[
    {user_id: 8, project_id: 1, role: "Ingegnere informatico", accepted: true},
    {user_id: 9, project_id: 1, role: "Grafico", accepted: true},
    {user_id: 10, project_id: 1, role: "Programmatore Senior", accepted: true},
    {user_id: 11, project_id: 1, role: "Grafico"},
    {user_id: 12, project_id: 1, role: "Full-stack Developer"},

    {user_id: 10, project_id: 2, role: "Programmatore Senior", accepted: true},
    {user_id: 11, project_id: 2, role: "Grafico", accepted: true},
    {user_id: 12, project_id: 2, role: "Programmatore Java", accepted: true},
    {user_id: 13, project_id: 2, role: "Ingegnere software", accepted: true},
    {user_id: 8, project_id: 2, role: "Grafico"},
    {user_id: 9, project_id: 2, role: "Full-stack Developer"},

    {user_id: 8, project_id: 3, role: "Ingegnere informatico", accepted: true},
    {user_id: 9, project_id: 3, role: "Grafico", accepted: true},
    {user_id: 10, project_id: 3, role: "Programmatore Senior", accepted: true},
    {user_id: 11, project_id: 3, role: "Grafico3d-Animazioni", accepted: true},
    {user_id: 12, project_id: 3, role: "Programmatore Junior", accepted: true},
    {user_id: 13, project_id: 3, role: "Front-end espert", accepted: true},
    {user_id: 5, project_id: 3, role: "Grafico"},
    {user_id: 4, project_id: 3, role: "Full-stack Developer"},

    {user_id: 9, project_id: 4, role: "Ingegnere informatico", accepted: true},
    {user_id: 11, project_id: 4, role: "Programmatore C++", accepted: true},
    {user_id: 3, project_id: 4, role: "Grafico"},
    {user_id: 2, project_id: 4, role: "Informatico"},
    {user_id: 6, project_id: 4, role: "Full-stack Developer"},

    {user_id: 8, project_id: 5, role: "Grafico"},
    {user_id: 9, project_id: 5, role: "Ingegnere informatico"},
    {user_id: 5, project_id: 5, role: "Programmatore Python"},
    {user_id: 10, project_id: 5, role: "Full-stack Developer"},

    {user_id: 13, project_id: 6, role: "Programmatore Java", accepted: true},
    {user_id: 8, project_id: 6, role: "Grafico", accepted: true}
]

Messaggess = [
    {project_id: 1, user_id: 8, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
    {project_id: 1, user_id: 9, body: "Etiam ut nulla justo."},
    {project_id: 1, user_id: 10, body: "Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet."},
    {project_id: 1, user_id: 2, body: "Fusce sed laoreet mauris."},

    {project_id: 2, user_id: 10, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
    {project_id: 2, user_id: 11, body: "Etiam ut nulla justo."},
    {project_id: 2, user_id: 12, body: "Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet."},
    {project_id: 2, user_id: 13, body: "Fusce sed laoreet mauris."},
    {project_id: 2, user_id: 3, body: "Donec porta mauris vel sapien suscipit feugiat."},
    
    {project_id: 3, user_id: 8, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
    {project_id: 3, user_id: 9, body: "Etiam ut nulla justo."},
    {project_id: 3, user_id: 10, body: "Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet."},
    {project_id: 3, user_id: 11, body: "Fusce sed laoreet mauris."},
    {project_id: 3, user_id: 12, body: "Donec porta mauris vel sapien suscipit feugiat."},
    {project_id: 3, user_id: 13, body: "Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo."},

    {project_id: 4, user_id: 9, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
    {project_id: 4, user_id: 11, body: "Etiam ut nulla justo."},
    {project_id: 4, user_id: 5, body: "Fusce sed laoreet mauris."},
    {project_id: 4, user_id: 11, body: "Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet."},

    {project_id: 6, user_id: 8, body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."},
    {project_id: 6, user_id: 8, body: "Etiam ut nulla justo."},
    {project_id: 6, user_id: 13, body: "Ut porta lobortis turpis, vel vestibulum tortor vestibulum sit amet."},
    {project_id: 6, user_id: 8, body: "Fusce sed laoreet mauris."},
    {project_id: 6, user_id: 13, body: "Donec porta mauris vel sapien suscipit feugiat."},
    {project_id: 6, user_id: 8, body: "Nulla vehicula, nisl non tempus ultricies, elit metus imperdiet massa, vulputate convallis enim purus nec leo."},
]

Userss.each do |user|
    User.create user
end

Projectss.each do |pr|
    Project.create pr
end

Joinss.each do |j|
    Join.create j
end

UserStoriess.each do |us|
    UserStory.create us
end

Messaggess.each do |mess|
    ChatMessage.create mess
end